### ISSUE TITLE
Charts in related entity popup section?

### ISSUE THREAD

**Issue by philippgaertner** [conterra/mapapps-related-tables#13]
Question: Is it possible to insert a chart in the related entity part or is the popup limited to a tabular format?

**Comment by matthiasstein** [comment]
This will be possible in the upcoming version 5. In this sample you can already have a look at it: https://demos.conterra.de/sandbox/resources/apps/relatedtables5
You can download the preview version here: https://github.com/conterra/mapapps-related-tables/releases/tag/5.0.0-SNAPSHOT

**Comment by matthiasstein** [comment]
Added in https://github.com/conterra/mapapps-related-tables/releases/tag/5.0.0
